db_file: "wordlist.db" # master wordlist database
intake_manually_sort_words: "data/inputs/manually_sort_words.json" # read file for sorting app


# Application configuration
generate_scored_wordlist:
  SCORED_WORDLIST: "data/matts_wordlist/scored_wordlist.json"
  SORTED_WORDLIST: "data/matts_wordlist/sorted_wordlist.json"
  SCORED_WORDLIST_TXT: "data/matts_wordlist/matts_wordlist.txt"